[app]
    # 源图片所在域名
    remote = ""

    # 源图片所在本地根目录
    local = ""

    # 是否预处理源图片
    prefetch = true
    prefetch_threads = 10

    # 支持持转换的格式：raw, webp, jpg, jpeg, png, gif, bmp, avif, heif
    # raw 只会转为原图格式，多个格式会返回最小文件对应的格式
    transform = ["raw"]

